### Songs Index Action
GET http://localhost:3000/songs.json
### Songs Show Action
GET http://localhost:3000/songs/1.json
### Songs Create Action
POST http://localhost:3000/songs.json
Content-Type: application/json

{
"title": "Untouchable",
"album": "AI Youngboy", 
"artist": "YoungBoy Never Broke Again",
"year": "2017"
}
### Songs Update Action
PATCH http://localhost:3000/songs/8.json
Content-Type: application/json

{
  "title": "Untouchable",
  "artist": "NBA YoungBoy"
}
### Songs Destroy Action
DELETE http://localhost:3000/songs/7.json 